// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ZpNpLhE0jQuwvY2dibybV7yTKLnUoi4',
    appId: '1:468227245058:web:471eefe30c170632b9531b',
    messagingSenderId: '468227245058',
    projectId: 'spotify-80117',
    authDomain: 'spotify-80117.firebaseapp.com',
    storageBucket: 'spotify-80117.appspot.com',
    measurementId: 'G-QCLSGCP4H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Rnyenpc7oDnNFcFkrqv2QVYvY_qn3F0',
    appId: '1:468227245058:android:c053a593bc7aae65b9531b',
    messagingSenderId: '468227245058',
    projectId: 'spotify-80117',
    storageBucket: 'spotify-80117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT1ZfQRSg1mFOTosAFERH56oSHKk5hTqU',
    appId: '1:468227245058:ios:8ababc54f7b4b54cb9531b',
    messagingSenderId: '468227245058',
    projectId: 'spotify-80117',
    storageBucket: 'spotify-80117.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT1ZfQRSg1mFOTosAFERH56oSHKk5hTqU',
    appId: '1:468227245058:ios:8ababc54f7b4b54cb9531b',
    messagingSenderId: '468227245058',
    projectId: 'spotify-80117',
    storageBucket: 'spotify-80117.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ZpNpLhE0jQuwvY2dibybV7yTKLnUoi4',
    appId: '1:468227245058:web:b59ab5d46634e6f6b9531b',
    messagingSenderId: '468227245058',
    projectId: 'spotify-80117',
    authDomain: 'spotify-80117.firebaseapp.com',
    storageBucket: 'spotify-80117.appspot.com',
    measurementId: 'G-RB5N9KCG0P',
  );
}
